config/routes.rb
Rails.application.routes.draw do
  get 'order1s/index'
  get 'order1s/show'
  get 'order1s/new'
  get 'orders/index'
  # get 'sampler/show', :path => '/sampler'
  get 'products/index'
  get 'products/show'
  get 'accounts/show'
  get '/home', to: "pages#home"
  get 'products/producers'
  get 'products/machines'
  get 'products/instruments'
  get 'products/other_kits'
  # get 'carts/show'

  # get 'carts/:id' => "carts#show", as: "cart"
  get 'cart' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"


  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Solves "No route matches [GET] '/users/sign_out'"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :products, only: [:index, :show]
  resources :sampler, only: [:index], :path => '/sampler'
  resources :sampler, only: [:show], :path => '/sampler/show'
  resources :carts, only: [:show], :path => '/user/cart'
  resources :orders, only: [:index], :path => '/user/order'
  resources :order_items
  resources :order1s

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order1, optional: true
  

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :order_items

  before_save :set_subtotal


  def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_idem.price*order_item.quantity : 0}.sum
  end


  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order1.rb
class Order1 < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  
  before_save :set_unit_price
  before_save :set_total


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # has_many :orders, foreign_key: :user_id
  # belongs_to :owner, class_name: "User"
  has_one_attached :photo
  has_one_attached :audio
  # has_many :samplers, foreign_key: :sampler_id
  has_many :order_items
  has_many :line_items, dependent: :destroy
end

app/models/sampler.rb
class Sampler < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    @cart = @current_cart
  end

  def index
    @products = Product.all
  end

  def create
    @products = Product.find(params[:product_id])
    @cart = Cart.new(cart_params)
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
  

  private
  
  def cart_params
    params.require(:cart).permit(:expire_on)
  end

  def product_params
    params.require(:product).permit(:name, :description, :content, :rating, :tags, :category, :price, :sound_name, :photo)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order1s_helper.rb
module Order1sHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sampler_helper.rb
module SamplerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetYourDrums</title>
    <%= favicon_link_tag "headphones.png" %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<!--HERO-->
<div class="hero-image">
  <div class="hero-text">
    <h1>STEP YOUR GAME UP</h1>
    <br>
    <%= link_to products_index_path do %>
      <button class="btn btn-danger">Explore the Kits</button>
    <% end %>
  </div>
</div>

<!--ICONS-->
<div class="container text-center mt-5">
  <h1>GET IT FROM THE BEST</h1>
  <p>Take a closer look at our features</p>
  <div class="home-card-wrapper d-flex">
    <div class="home-card mx-4">
      <img class="mb-3" src="soundwave.svg"/>
      <h4 class="home-title">Producer kits</h4>
      <p class="home-content text-center">Directly sampled or inspired drum sounds from the best producers in the game</p>
    </div>
    <div class="home-card mx-4">
      <img class="mb-3" src="speaker.svg"/>
      <h4 class="home-title">Machine kits</h4>
      <p class="home-content text-center">Know for their iconic sounds, get it straight from the TR-808, 909, Lynn, or MPC libraries</p>
    </div>
    <div class="home-card mx-4">
      <img class="mb-3" src="adjust.svg"/>
      <h4 class="home-title">Instruments kits</h4>
      <p class="home-content text-center">Live acoustic instrument libraries. Contains piano, rhodes, horns, strings, flutes and more</p>
    </div>
  </div>
</div>

<!--CAROUSEL-->
<h1 class="latest-kits container text-center mt-5">OUR LATEST KITS</h1>
<div class="carousel mt-3">
  <%= render "shared/carousel" %>
</div>

<!--MPC-->
<div class="mpc-banner container">
  <h1 class="text-center">TRY THE<span class=""> KITS </span>ON OUR <span class="red">SAMPLER</span></h1>
  <div class="mpc-container">
    <%= link_to sampler_index_path do %>
      <%= render 'shared/mpc' %>
    <% end %>
  </div>
</div>

app/views/shared/_cardHomePage.html.erb
<div class="carousel-item col-md-4 active">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="jd.jpg" alt="slide 1">
        <div class="p-3">
          <div class="div">
            <h2>J Dilla</h2>
            <h6><span class="">119 sounds</span></h6>
            <div class="btn btn-success">$29,99</div>	
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="primo.jpg" alt="slide 2">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>         
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="dre.jpg" alt="slide 3">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="jd.jpg" alt="slide 4">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="jd.jpg" alt="slide 5">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="jd.jpg" alt="slide 6">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="carousel-item col-md-4">
  <div class="map-container">
    <div>
      <div class="card-instrument-inline m-4">
        <img class="img-fluid d-block" src="jd.jpg" alt="slide 7">
        <div class="card-instrument-inline-infos p-3">
          <h2>J Dilla</h2>
          <h6><span class="text-instrument-inline">119 sounds</span></h6>
          <div class="d-flex justify-content-end">
            <div class="btn btn-success">$29,99</div>	
          </div>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_carousel.html.erb
<div class="carousel-inner d-flex">
  <% @products.each do |product| %>

    <div class="carousel-item active">
      <div class="row d-flex justify-content-between">
        <div class="col-md-3">
          <div class="card carousel-card" style="width: 18rem;">
            <%= cl_image_tag product.photo.key, width: 250, height: 169, crop: :fill, class:"image-center" %>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text"><%= product.content %></p>
              <a href="#" class="btn btn-success">Check it out!</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

<!--
<% @products.each do |product| %>
  <div class="carousel-item col-md-4 active">
    <div class="map-container">
      <div class="card mb-3" style="max-width: 540px; max-height: 170px">
        <div class="row no-gutters">
          <div class="col-md-4 img-fluid image">
            <%= cl_image_tag product.photo.key, width: 180, height: 169, crop: :fill %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text description mt-3"><%= product.content %></p>
              <div class="price d-flex justify-content-between">
                <p class="card-text text-right"><small class="text-muted"><%= link_to product_path(product), class: "btn btn-success" do %>
                  $<%= product.price %>0
                <% end %></small></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>



<% @products.each do |product| %>
  <div class="carousel-item col-md-4">
    <div class="map-container">
      <div>
        <div class="card-instrument-inline m-4">
          <img class="img-fluid d-block" src="<%= cl_image_tag product.photo.key, crop: :fill %>" alt="slide 1">
          <div class="card-instrument-inline-infos p-3">
            <%= product.name %> <h6><span class="text-instrument-inline"><%= product.content %></span></h6>
            <div class="d-flex justify-content-end">
              <p class="card-text text-right"><small class="text-muted"><%= link_to product_path(product), class: "btn btn-success" do %>
                  $<%= product.price %>0
                <% end %></small></p>	
            </div>         
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


  <div class="carousel-item col-md-4">
    <div class="map-container">
      <div>
        <div class="card-instrument-inline m-4">
          <img class="img-fluid d-block" src="dre.jpg" alt="slide 3">
          <div class="card-instrument-inline-infos p-3">
            <h2>Dr. Dre</h2> <h6><span class="text-instrument-inline">119 sounds</span></h6>
            <div class="d-flex justify-content-end">
              <div class="btn btn-success">$29,99</div>	
            </div>          
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="carousel-item col-md-4">
    <div class="map-container">
      <div>
        <div class="card-instrument-inline m-4">
          <img class="img-fluid d-block" src="jd.jpg" alt="slide 4">
          <div class="card-instrument-inline-infos p-3">
            <h2>J Dilla</h2>
            <h6><span class="text-instrument-inline">119 sounds</span></h6>
            <div class="d-flex justify-content-end">
              <div class="btn btn-success">$29,99</div>	
            </div>          
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_card_product.html.erb
<% @products.each do |product| %>
<!-- max-height makes text disapear when on smaller screen -->
  <div class="item">
    <div class="card mb-3 stacked--left" style="max-width: 540px; max-height: 170px">
      <div class="row no-gutters">
        <div class="col-md-4">
          <%= link_to product_path(product) do %>
            <%= cl_image_tag product.photo.key, width: 180, height: 169, crop: :fill, class:'product-image' %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">
            <%= link_to product_path(product) do %>
              <%= product.name %><span class="price-span"><%= number_to_currency(product.price) %></span>
            <% end %></h5>
            <p class="card-text description mt-3">
            <%= link_to product_path(product) do %>
              <%= product.content %></p>
            <% end %>
            <div class="add-to-cart d-flex justify-content-between">
              <p class="card-text" style="color:red; font-weight:600"><%= link_to sampler_path(product), class: "btn btn-outline-danger" do %>Try Now!</p><% end %></small></p>
              
              <p><small class="text-muted"><%= button_to line_items_path(:product_id => product.id), class: "btn btn-success" do %>
                Add to cart
              <% end %></small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_carousel.html.erb
<div class="container">
	<div class="row blog">
		<div class="col-md-12">
			<div id="blogCarousel" class="carousel slide" data-ride="carousel">

				<%= render 'shared/card_carousel' %>

				<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>	
		</div>
	</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-headphones-alt"></i> GetYourDrums
  </div>
</div>

app/views/shared/_mpc-producers.html.erb
<div class="container mpc-wrapper">
  <div class="frame">
    <div class="screen-wrapper">
      <p id="screenName" class="screen-name"><%= @product.name %></p>
      <p class="screen-content"><%= @product.content %></p>
    </div>
    <div class="brand-wrapper">
      <div class="brand">SAMPLER</div>
      <div class="brand2">Beatmakers.com</div>
    </div>
    <div class="pads-wrapper">
      <div class="pad1">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-1 **********<audio id="audio"><source src="/home/stephan/get-your-drums/app/assets/sounds/sound.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad2">
        <div class= "pad-sound" onclick="document.getElementById('audio2').play()"> Pad-2 **********<audio id="audio2"><source src="sound2.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad3">
        <div class= "pad-sound" onclick="document.getElementById('audio3').play()"> Pad-3 **********<audio id="audio3"><source src="sound3.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad4">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-4 **********<audio id="audio"><source src="<% @products.first.audio %>" type="audio/wav"></audio></div>
      </div>

      <div class="pad5">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-5 **********<audio id="audio"><source src="sound.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad6">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-6 **********<audio id="audio"><source src="sound.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad7">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-7 **********<audio id="audio"><source src="sound.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad8">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-8 **********<audio id="audio"><source src="sound.wav" type="audio/wav"></audio></div>
      </div>

      <div class="pad9">
        <div class= "pad-sound" onclick="document.getElementById('audio').play()"> Pad-9 **********<audio id="audio"><source src="sound.wav" type="audio/wav"></audio></div>
      </div>
    </div>
    <div class="scroller">
      <div class="scroller-circle"></div>
    </div>
    <div class="buttons-wrapper">
      <div class="rec">
        <div class="rec-symbol"></div>
      </div>
      <div class="play">
        <div class="play-symbol"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div>
  <%= link_to sampler_index_path do %>
    <div class="mpc-logo nav-item">
      <div>
        
            <%= cl_image_tag("https://res.cloudinary.com/stephan/image/upload/v1623138044/get-your-drums/mpc.png",
        width: 88, height: 67, crop: :fill) %>
          
      </div>
      <div class="mpc-text">TRY IT NOW!</div>
    </div>
  <% end %>
    <!--
    <%= link_to home_path do %>
          <%= cl_image_tag("https://res.cloudinary.com/stephan/image/upload/v1624437059/get-your-drums/logo-new2.png", class:"icon navbar-brand p-0") %>
    <% end %>
    <%# <div class="speaker small flex-center circle1">
      <div class="ring small flex-center">
        <div class="b">B</div> %> -->
    
  </div>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="item-list navbar-nav mr-auto d-flex justify-content-center">
      <!--<li class="item-title nav-item">
        <%= link_to "All Drum Kits", products_index_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      </li>-->
      <li class="item-title nav-item">
        <%= link_to "Producers kits", products_producers_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      </li>
      <li class="item-title nav-item">
        <%= link_to "Machines kits", products_machines_path, class: "nav-link" %>
        <span class="sr-only">(current)</span></a>
      </li>
      <li class="item-title nav-item">
        <%= link_to "Instruments kits", products_instruments_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      </li>
      <li class="item-title nav-item">
        <%= link_to "Other Kits", products_other_kits_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      </li>

      <!--
      <ul class="mpc-ul">
        <li class="nav-item mb-2 mpc-icon">
          <div class="mpc-text">Try Now!</div>
          <div>
            <%= link_to sampler_index_path do %>
                <%= cl_image_tag("https://res.cloudinary.com/stephan/image/upload/v1623138044/get-your-drums/mpc.png",
            width: 80, height: 60, crop: :fill) %>
              <% end %>
          </div> 
          
        </li>
      </ul> -->
      
        <!-- <%= link_to '""', home_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
      </li> -->

      <!--DROPDOWN-->
      <%# <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> %>
    </ul>

    <div class="login">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          
            <li class="nav-item active">
            <div class="">
              <%= link_to cart_path do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            </div> 
            </li>
                  
          <li class="nav-item active">
            <%= link_to "My Account", accounts_show_path, class: "nav-link mr-2" %><span class="sr-only">(current)</span>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-secondary" %>
          </li>
        <% else %>
          <li class="login-btn nav-item active">            
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>            
          </li>
          <li class="nav-item active">            
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link btn btn-success" %>
          </li>
        <% end %>
      </ul>
    </div>
    <!--SEARCHBAR-->
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

<!-- LOGO BAR -->
<nav id="logo" class="navbar-logo navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-center align-items-baseline pt-0">
  <ul class="navbar-nav">
    <%= link_to "Beatmakers.com", home_path, class:"logo", style:"font-family: Pacifico; font-size: 25px;" %>
  </ul>
</nav>

app/views/shared/_sidebar_producers.html.erb
<% @producers.each do |producer| %>

  <ul class="submenu collapse list-unstyled" id="homeSubmenu1">
    <li class="producer-list">
      <%= link_to sampler_path(producer), id:"clicker" do %>
        <%= producer.name %>
      <% end %>
    </li>
  </ul>

<% end %>

<script>$("#clicker").load("app/views/sampler/show.html.erb #mydiv");</script>

app/views/shared/_single_product.html.erb
<div class="item">
  <div class="card mb-3 stacked--left" style="max-width: 540px; max-height: 170px">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= link_to product_path(@product) do %>
          <%= cl_image_tag @product.photo.key, width: 180, height: 169, crop: :fill, class:'product-image' %>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">
          <%= link_to product_path(@product) do %>
            <%= @product.name %><span class="price-span"><%= number_to_currency(@product.price) %></span>
          <% end %></h5>
          <p class="card-text description mt-3">
          <%= link_to product_path(@product) do %>
            <%= @product.content %></p>
          <% end %>
          <div class="add-to-cart d-flex justify-content-between">
            <p class="card-text" style="color:red; font-weight:600"><%= link_to sampler_path(@product), class: "btn btn-outline-danger" do %>Try Now!</p><% end %></small></p>
            <td>
            <p><small class="text-muted"><%= button_to line_items_path(:product_id => @product.id), class: "btn btn-success" do %>
                Add to cart
            <% end %></small></p>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<!-- SECOND TRY
<div class="single-card">
  <%= cl_image_tag @product.photo.key, width: 250, height: 169, crop: :fill, class:"image-center" %>
  <div class="card-body">
    <h5 class="card-title"><%= @product.name %></h5>
    <p class="card-text"><%= @product.content %></p>
    <a href="#" class="btn btn-success">Add to Cart</a>
  </div>
</div>-->

        