config/routes.rb
Rails.application.routes.draw do
  get 'order1s/index'
  get 'order1s/show'
  get 'order1s/new'
  get 'orders/index'
  # get 'sampler/show', :path => '/sampler'
  get 'products/index'
  get 'products/show'
  get 'accounts/show'
  get '/home', to: "pages#home"
  get 'products/producers'
  get 'products/machines'
  get 'products/instruments'
  get 'products/other_kits'
  # get 'carts/show'

  # get 'carts/:id' => "carts#show", as: "cart"
  get 'cart' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"


  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Solves "No route matches [GET] '/users/sign_out'"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :products, only: [:index, :show]
  resources :sampler, only: [:index], :path => '/sampler'
  resources :sampler, only: [:show], :path => '/sampler/show'
  resources :carts, only: [:show], :path => '/user/cart'
  resources :orders, only: [:index], :path => '/user/order'
  resources :order_items
  resources :order1s

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order1, optional: true
  

  # LOGIC
  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :order_items

  before_save :set_subtotal


  def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_idem.price*order_item.quantity : 0}.sum
  end


  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order1.rb
class Order1 < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  
  before_save :set_unit_price
  before_save :set_total


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price * quantity
  end


  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # has_many :orders, foreign_key: :user_id
  # belongs_to :owner, class_name: "User"
  has_one_attached :photo
  has_one_attached :audio
  # has_many :samplers, foreign_key: :sampler_id
  has_many :order_items
  has_many :line_items, dependent: :destroy
end

app/models/sampler.rb
class Sampler < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    @cart = @current_cart
  end

  def index
    @products = Product.all
  end

  def create
    @products = Product.find(params[:product_id])
    @cart = Cart.new(cart_params)
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
  

  private
  
  def cart_params
    params.require(:cart).permit(:expire_on)
  end

  def product_params
    params.require(:product).permit(:name, :description, :content, :rating, :tags, :category, :price, :sound_name, :photo)
  end
end

app/controllers/order1s_controller.rb
class Order1sController < ApplicationController
  def index
    @orders = Order1.all
  end

  def show
    @order = Order1.find(params[:id])
  end

  def new
    @order = Order1.new
  end

  def create
    @order = Order1.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      # item.cart_id = nil
      item.update(cart_id: nil)
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end
  
  private

  def order_params
    params.require(:order1).permit(:name, :email, :address, :pay_method)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  
  
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/order1s_helper.rb
module Order1sHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sampler_helper.rb
module SamplerHelper
end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of #{current_order.subtotal }$", cart_path%>

<!-- Replaces 'cart_path' by 'carts_show_path'
<%= link_to "#{current_order.order_items.size} items with a value of #{current_order.subtotal }$", carts_show_path%>
-->

app/views/carts/_carts_item.html.erb
<% @order_items.each do |item| %>

    <h3><%= item.product.title %></h3>
    <h5><%= item.product.price %></h5>


    <%= form_for item, remote: true do |f| %>
        <%= f.hidden_field :product_id, :value => item.product.id %>
        <%= f.number_field :quantity, :value => item.quantity.to_i %>
        <%= f.submit "Update Card "%>
        <%= link_to "Remove Items", order_item_path(item), method: :delete, remote: true%>
    <% end %>
    <h2>Subtotal: <%= item.total %></h2>

<% end %>




<h3>Your current card value has a subtotal of: <%= current_order.subtotal %></h3>

app/views/carts/show.html.erb
<!--
<% @order_items.each do |item| %>
  <h3><%= item.product.title %></h3>
  <h5><%= item.product.price %></h5>
<% end %>

<div id="cart-item">
  <%= render 'carts_item'%>
</div> -->

<h2>Cart show</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.product.name %>/ Price: <%= number_to_currency(line_item.product.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
    </li>
    # See lineItem section below for explanation of line_item links
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
    #
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
# See Order section below for explanation of new_order_path
<%= link_to "Proceed to checkout", new_order1_path %><br>
#
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"} %>

app/views/order1s/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Line Items: </p>
  <ul>
    <% order.line_items.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/order1s/new.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/order1s/show.html.erb
<h1>Order1s#show</h1>
<p>Find me in app/views/order1s/show.html.erb</p>

app/views/orders/index.html.erb
<div class="cart-body">
  <div class="pb-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">
          <!-- Shopping cart table -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Product</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Price</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Quantity</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Remove</div>
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row" class="border-0">
                    <div class="p-2">
                      <img src="https://res.cloudinary.com/mhmd/image/upload/v1556670479/product-1_zrifhn.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                      <div class="ml-3 d-inline-block align-middle">
                        <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">Timex Unisex Originals</a></h5><span class="text-muted font-weight-normal font-italic d-block">Category: Watches</span>
                      </div>
                    </div>
                  </th>
                  <td class="border-0 align-middle"><strong>$79.00</strong></td>
                  <td class="border-0 align-middle"><strong>3</strong></td>
                  <td class="border-0 align-middle"><a href="#" class="text-dark"><i class="fa fa-trash"></i></a></td>
                </tr>
                <tr>
                  <th scope="row">
                    <div class="p-2">
                      <img src="https://res.cloudinary.com/mhmd/image/upload/v1556670479/product-3_cexmhn.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                      <div class="ml-3 d-inline-block align-middle">
                        <h5 class="mb-0"><a href="#" class="text-dark d-inline-block">Lumix camera lense</a></h5><span class="text-muted font-weight-normal font-italic">Category: Electronics</span>
                      </div>
                    </div>
                  </th>
                  <td class="align-middle"><strong>$79.00</strong></td>
                  <td class="align-middle"><strong>3</strong></td>
                  <td class="align-middle"><a href="#" class="text-dark"><i class="fa fa-trash"></i></a>
                  </td>
                </tr>
                <tr>
                  <th scope="row">
                    <div class="p-2">
                      <img src="https://res.cloudinary.com/mhmd/image/upload/v1556670479/product-2_qxjis2.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                      <div class="ml-3 d-inline-block align-middle">
                        <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block">Gray Nike running shoe</a></h5><span class="text-muted font-weight-normal font-italic">Category: Fashion</span>
                      </div>
                    </div>
                    <td class="align-middle"><strong>$79.00</strong></td>
                    <td class="align-middle"><strong>3</strong></td>
                    <td class="align-middle"><a href="#" class="text-dark"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
              </tbody>
            </table>
          </div>
          <!-- End -->
        </div>
      </div>

      <div class="row py-5 p-4 bg-white rounded shadow-sm">
        <div class="col-lg-6">
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Coupon code</div>
          <div class="p-4">
            <p class="font-italic mb-4">If you have a coupon code, please enter it in the box below</p>
            <div class="input-group mb-4 border rounded-pill p-2">
              <input type="text" placeholder="Apply coupon" aria-describedby="button-addon3" class="form-control border-0">
              <div class="input-group-append border-0">
                <button id="button-addon3" type="button" class="btn btn-dark px-4 rounded-pill"><i class="fa fa-gift mr-2"></i>Apply coupon</button>
              </div>
            </div>
          </div>
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Instructions for seller</div>
          <div class="p-4">
            <p class="font-italic mb-4">If you have some information for the seller you can leave them in the box below</p>
            <textarea name="" cols="30" rows="2" class="form-control"></textarea>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Order summary </div>
          <div class="p-4">
            <p class="font-italic mb-4">Shipping and additional costs are calculated based on values you have entered.</p>
            <ul class="list-unstyled mb-4">
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Order Subtotal </strong><strong>$390.00</strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Shipping and handling</strong><strong>$10.00</strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Tax</strong><strong>$0.00</strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                <h5 class="font-weight-bold">$400.00</h5>
              </li>
            </ul><a href="#" class="btn btn-dark rounded-pill py-2 btn-block">Procceed to checkout</a>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
</div>